@local=http://localhost:3000


POST {{local}}/api/users
Content-Type: application/json

{
    "name": "shnono",
    "email": "shnono@email.com",
    "password": "Aa123456",
    "biz": "true"
}

###

POST {{local}}/api/auth
Content-Type: application/json

{
    "email": "shnono@email.com",
    "password": "Aa123456"
}

###
GET {{local}}/api/users/me 
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzYzMDQzNTU5OTA0MDhlMzk1M2VmYjgiLCJiaXoiOnRydWUsImlhdCI6MTczNDU0MjQwM30.zvhGV906UzDHfBpruG2CZ5aP23LjEIIqBGt1kUwDBCs