@local=http://localhost:3000


GET {{local}}/api/users
Content-Type: application/json

{
    "name": "noam",
    "email": "email@email.com",
    "password": "Aa123456",
    "biz": "true"
}

###

POST {{local}}/api/auth
Content-Type: application/json

{
    "email": "email@email.com",
    "password": "Aa123456"
}

###
GET {{local}}/api/users/me 
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzYwNWExNTkwYzdhZTEyNDk1ZmYzZDEiLCJiaXoiOnRydWUsImlhdCI6MTczNDYyNTMwNH0.uqT8l8CAuoz0sEjNXjx7D0wpgDWpa2iOyY2Yjs0_Avk

###

POST {{local}}/api/cards
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzYwNWExNTkwYzdhZTEyNDk1ZmYzZDEiLCJiaXoiOnRydWUsImlhdCI6MTczNDYzNDExMn0.D_vl1S3bKsqwdd4a6vJtS-WYQXXa_eGA0vteCNd-u20
Content-Type: application/json

{
    "bizName": "IKEA",
    "bizPhone": "042244661",
    "bizAddress": "Sweeden Stockholm",
    "bizDescription": "A Place to take your girl to date where you argue about which side the chaise lounge will be"
}